version: '3.7'

services:

  db:
    image: postgres:10.11
    container_name: database
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin123
    ports:
      - 5432:5432
    networks:
      - stack
    command: -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all -c track_activity_query_size=2048

  pgAdmin:
    image: dpage/pgadmin4:4.15
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@local.local"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - 8081:80
    networks:
      - stack

networks:
  stack: {}
volumes:
  filebeat: {}
