version: '3.8'

services:

  db:
    image: postgres:15.2
    container_name: database
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stack
    command: -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all -c track_activity_query_size=2048

  pgAdmin:
    image: dpage/pgadmin4:6.20
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "kasetesting@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - 8081:80
    networks:
      - stack

networks:
  stack: {}
volumes:
  pgdata:
